title: 枫声 Yongfeng's Blog
description: Yongfeng Zhang's blog full-stack software engineer

url: http://localhost:4000/
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: redcarpet
highlighter: pygments
gems: ['jekyll-paginate', 'jekyll-multiple-languages']
paginate: 5

navigation:
   en:
     - title: Home
       url: /index.html
     - title: About
       url: /about
     - title: Contact
       url: /contact
   cn:
     - title: 主页
       url: /cn/
     - title: 关于
       url: /cn/about
     - title: 联系我
       url: /cn/contact

social:
   github: freedombird9
   twitter: freedombird9
   facebook: yongfeng.zhangfree
   email: yf.zhangfree@gmail.com

google_analytics: ""

# -----------------

# Multiple languages
languages:          ['en', 'cn']

# If not config, the first of languages will be the default
language_default:   "en"

# -----------------
